global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'duclkde170045@fpt.edu.vn'
  smtp_auth_username: 'duclkde170045@fpt.edu.vn'
  smtp_auth_password: 'dgdpibxnvtyfikcz'

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
      - to: 'lekhanhduccc@gmail.com'
        send_resolved: true
