global:
  scrape_interval: 10s  

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/metrics' 
    scheme: http  
    static_configs:
      - targets: ['localhost:9090']  

  - job_name: 'application'
    metrics_path: '/metrics'
    scheme: https
    tls_config:
      insecure_skip_verify: true 
    static_configs:
      - targets: ['host.docker.internal:7207']